"""baseline schema

Revision ID: dd006ba3b06d
Revises: 
Create Date: 2026-09-08 20:46:53.206776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd006ba3b06d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pg_trgm must exist before idx_messages_text_trgm (further down, inside the autogenerated 'messages' block) can be created
    # - it supplies the gin_trgm_ops operator class that index is built with.
    # IF NOT EXISTS: harmless if docker/init/01-extensions.sql already enabled it for this database;
    # keeps this migration self-contained and re-runnable against a database provisioned any other way too.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('chat_selector', sa.Text(), nullable=True),
    sa.Column('chats_total', sa.Integer(), nullable=True),
    sa.Column('chats_done', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('messages_stored', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('messages_skipped', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'cancelled', 'error')", name='ck_backfill_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_migrations',
    sa.Column('old_chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('new_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('migrated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('old_chat_id')
    )
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('chat_type', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('edited_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_message_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.CheckConstraint("chat_type IN ('group', 'supergroup', 'channel', 'private')", name='ck_chats_chat_type'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index('idx_chats_last_message_at', 'chats', ['last_message_at'], unique=False)
    op.create_table('senders',
    sa.Column('sender_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('sender_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('edited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.sender_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_chat_date', 'messages', ['chat_id', 'date'], unique=False)
    op.create_index('idx_messages_date', 'messages', ['date'], unique=False)
    op.create_index('idx_messages_is_deleted_partial', 'messages', ['chat_id', 'date'], unique=False, postgresql_where=sa.text('is_deleted IS true'))
    op.create_index('idx_messages_is_edited_partial', 'messages', ['chat_id', 'date'], unique=False, postgresql_where=sa.text('is_edited IS true'))
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_text_trgm', 'messages', ['text'], unique=False, postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.create_index('idx_messages_tg_id_chat', 'messages', ['tg_message_id', 'chat_id'], unique=True)
    op.create_table('message_deletions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('text_snapshot', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by_inference', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('inference_confidence', sa.Text(), nullable=True),
    sa.CheckConstraint("deleted_by_inference IN ('channel_admin', 'self', 'unknown')", name='ck_message_deletions_deleted_by_inference'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_deletions_message_id', 'message_deletions', ['message_id'], unique=False)
    op.create_table('message_edits',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_edits_message_id', 'message_edits', ['message_id'], unique=False)
    # ### end Alembic commands ###

    # -------------------------------------------------------------------
    # Denormalized chats-counter triggers.
    # Not representable as SQLAlchemy Core Table objects (no trigger/function abstraction there - see db/schema.py's module docstring),
    # so they're written directly here as raw SQL.
    # Ports SQLite migration 005's 6 triggers to PL/pgSQL, with two real (not just syntactic) differences:
    #
    #   - SQLite's MIN(a, b)/MAX(a, b) are 2-argument SCALAR functions (smallest/largest of the arguments).
    #     Postgres's MIN/MAX are aggregate-only - the scalar equivalents are LEAST()/GREATEST().
    #   - is_deleted/is_edited are native BOOLEAN here (they were INTEGER 0/1 in SQLite),
    #     so arithmetic on them (message_count +/- 1 per row)
    #     needs an explicit ::int cast - Postgres won't implicitly convert a boolean to a number the way SQLite would.
    #
    # No backfill statement here (SQLite migration 005 had one, to populate counters for messages that already existed before that migration ran).
    # It doesn't apply at this baseline: this migration runs against an empty database,
    # before the SQLite->Postgres data migration script (separate step) loads any rows, so there's nothing yet to backfill.
    # That script is responsible for the historical archive's counts being correct on load - these triggers only take over from that point on.
    # -------------------------------------------------------------------

    op.execute("""
        CREATE FUNCTION chats_counters_ai() RETURNS TRIGGER AS $$
        BEGIN
            UPDATE chats SET
                message_count = message_count + 1,
                deleted_count = deleted_count + NEW.is_deleted::int,
                edited_count = edited_count + NEW.is_edited::int,
                first_message_at = LEAST(COALESCE(first_message_at, NEW.date), NEW.date),
                last_message_at = GREATEST(COALESCE(last_message_at, NEW.date), NEW.date),
                last_message_preview = CASE
                    WHEN NEW.date >= COALESCE(last_message_at, NEW.date)
                    THEN SUBSTR(NEW.text, 1, 80)
                    ELSE last_message_preview
                END
            WHERE chat_id = NEW.chat_id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER chats_counters_ai AFTER INSERT ON messages
        FOR EACH ROW EXECUTE FUNCTION chats_counters_ai()
    """)

    op.execute("""
        CREATE FUNCTION chats_counters_au_deleted() RETURNS TRIGGER AS $$
        BEGIN
            UPDATE chats SET deleted_count = deleted_count + (NEW.is_deleted::int - OLD.is_deleted::int)
            WHERE chat_id = NEW.chat_id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER chats_counters_au_deleted AFTER UPDATE OF is_deleted ON messages
        FOR EACH ROW WHEN (NEW.is_deleted IS DISTINCT FROM OLD.is_deleted)
        EXECUTE FUNCTION chats_counters_au_deleted()
    """)

    op.execute("""
        CREATE FUNCTION chats_counters_au_edited() RETURNS TRIGGER AS $$
        BEGIN
            UPDATE chats SET edited_count = edited_count + (NEW.is_edited::int - OLD.is_edited::int)
            WHERE chat_id = NEW.chat_id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER chats_counters_au_edited AFTER UPDATE OF is_edited ON messages
        FOR EACH ROW WHEN (NEW.is_edited IS DISTINCT FROM OLD.is_edited)
        EXECUTE FUNCTION chats_counters_au_edited()
    """)

    op.execute("""
        CREATE FUNCTION chats_counters_au_chatid() RETURNS TRIGGER AS $$
        BEGIN
            UPDATE chats SET
                message_count = message_count - 1,
                deleted_count = deleted_count - OLD.is_deleted::int,
                edited_count = edited_count - OLD.is_edited::int
            WHERE chat_id = OLD.chat_id;

            UPDATE chats SET
                message_count = message_count + 1,
                deleted_count = deleted_count + NEW.is_deleted::int,
                edited_count = edited_count + NEW.is_edited::int,
                first_message_at = LEAST(COALESCE(first_message_at, NEW.date), NEW.date),
                last_message_at = GREATEST(COALESCE(last_message_at, NEW.date), NEW.date),
                last_message_preview = CASE
                    WHEN NEW.date >= COALESCE(last_message_at, NEW.date)
                    THEN SUBSTR(NEW.text, 1, 80)
                    ELSE last_message_preview
                END
            WHERE chat_id = NEW.chat_id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER chats_counters_au_chatid AFTER UPDATE OF chat_id ON messages
        FOR EACH ROW WHEN (NEW.chat_id IS DISTINCT FROM OLD.chat_id)
        EXECUTE FUNCTION chats_counters_au_chatid()
    """)

    op.execute("""
        CREATE FUNCTION chats_counters_ad() RETURNS TRIGGER AS $$
        BEGIN
            UPDATE chats SET
                message_count = message_count - 1,
                deleted_count = deleted_count - OLD.is_deleted::int,
                edited_count = edited_count - OLD.is_edited::int
            WHERE chat_id = OLD.chat_id;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER chats_counters_ad AFTER DELETE ON messages
        FOR EACH ROW EXECUTE FUNCTION chats_counters_ad()
    """)

    op.execute("""
        CREATE FUNCTION chats_counters_au_text() RETURNS TRIGGER AS $$
        BEGIN
            UPDATE chats SET last_message_preview = SUBSTR(NEW.text, 1, 80)
            WHERE chat_id = NEW.chat_id AND last_message_at = NEW.date;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("""
        CREATE TRIGGER chats_counters_au_text AFTER UPDATE OF text ON messages
        FOR EACH ROW WHEN (NEW.text IS DISTINCT FROM OLD.text)
        EXECUTE FUNCTION chats_counters_au_text()
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Triggers/functions must go before the tables below are dropped - they reference chats and messages directly,
    # so dropping the tables first would fail
    # (or, worse, silently strand orphaned function definitions depending on drop order - dropping them explicitly first avoids depending on that being the case).
    op.execute("DROP TRIGGER IF EXISTS chats_counters_au_text ON messages")
    op.execute("DROP FUNCTION IF EXISTS chats_counters_au_text()")
    op.execute("DROP TRIGGER IF EXISTS chats_counters_ad ON messages")
    op.execute("DROP FUNCTION IF EXISTS chats_counters_ad()")
    op.execute("DROP TRIGGER IF EXISTS chats_counters_au_chatid ON messages")
    op.execute("DROP FUNCTION IF EXISTS chats_counters_au_chatid()")
    op.execute("DROP TRIGGER IF EXISTS chats_counters_au_edited ON messages")
    op.execute("DROP FUNCTION IF EXISTS chats_counters_au_edited()")
    op.execute("DROP TRIGGER IF EXISTS chats_counters_au_deleted ON messages")
    op.execute("DROP FUNCTION IF EXISTS chats_counters_au_deleted()")
    op.execute("DROP TRIGGER IF EXISTS chats_counters_ai ON messages")
    op.execute("DROP FUNCTION IF EXISTS chats_counters_ai()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_edits_message_id', table_name='message_edits')
    op.drop_table('message_edits')
    op.drop_index('idx_message_deletions_message_id', table_name='message_deletions')
    op.drop_table('message_deletions')
    op.drop_index('idx_messages_tg_id_chat', table_name='messages')
    op.drop_index('idx_messages_text_trgm', table_name='messages', postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_is_edited_partial', table_name='messages', postgresql_where=sa.text('is_edited IS true'))
    op.drop_index('idx_messages_is_deleted_partial', table_name='messages', postgresql_where=sa.text('is_deleted IS true'))
    op.drop_index('idx_messages_date', table_name='messages')
    op.drop_index('idx_messages_chat_date', table_name='messages')
    op.drop_table('messages')
    op.drop_table('senders')
    op.drop_index('idx_chats_last_message_at', table_name='chats')
    op.drop_table('chats')
    op.drop_table('chat_migrations')
    op.drop_table('backfill_runs')
    # ### end Alembic commands ###

    # pg_trgm is deliberately NOT dropped here.
    # Extensions are effectively a shared, database-wide resource - a later migration could reasonably depend on it existing,
    # and `alembic downgrade` targeting a specific revision doesn't guarantee this migration is the last one undone.
    # Re-running upgrade() later is unaffected either way (IF NOT EXISTS).