"""
Defines all database tables as SQLAlchemy Core Table objects (not the ORM - see db/connection.py's module docstring for why Core was chosen for this project).

This module is the single source of truth for the schema shape. It is consumed by:
  - Alembic, which autogenerates migrations by diffing the live database against `metadata` (see alembic/env.py, added in the Alembic-init step of this migration).
  - db/queries.py and db/read_queries.py, which build statements against these Table objects instead of hand-written SQL strings.

Table overview:
  - chats               : one row per Telegram chat/channel/DM, plus denormalized per-chat counters (message_count, last_message_at, etc.)
  - senders             : one row per Telegram user we've seen
  - messages            : every archived message
  - message_edits       : full edit history for messages that were changed
  - message_deletions   : full deletion history for messages that were deleted
  - chat_migrations     : maps an old (pre-migration) chat_id to its canonical new one
  - backfill_runs       : records each time a backfill is run

Schema history (SQLite era, db/migrations/001-005 - see that package for the full reasoning behind each;
this file represents the END state of all of them, not the incremental steps):
  v1 (initial)  : chats, senders, messages, message_edits
  v2            : chats.username added
  v3            : message_deletions table added
  v4            : messages_fts (FTS5 trigram) added for substring/Cyrillic search
  v5            : chat_migrations table added
  v6            : backfill_runs table added
  v7 (SQLite)   : message_deletions.deleted_by_inference + inference_confidence added
                  (001), then the CHECK constraint narrowed to channel-only inference
                  (002), then widened again for Saved Messages 'self' (003)
  v8 (SQLite)   : chats denormalized counter columns + sync triggers added (005)

PostgreSQL migration changes (this file, current):
  - INTEGER PRIMARY KEY AUTOINCREMENT -> BigInteger with Identity() (GENERATED BY DEFAULT AS IDENTITY).
    BigInteger (not plain Integer) everywhere a Telegram ID is stored:
    Telegram channel/chat IDs routinely exceed Postgres's 32-bit `integer` range, where SQLite's INTEGER was already 64-bit and hid this.
  - DATETIME (stored as ISO-8601 TEXT in SQLite) -> TIMESTAMPTZ.
    Native timezone-aware timestamps, sortable/comparable by Postgres itself instead of by string comparison.
  - is_edited / is_deleted: INTEGER 0/1 -> native BOOLEAN.
    Decided over keeping 0/1 because psycopg maps BOOLEAN straight to Python True/False - one less "is 1 truthy here?"
    question for every call site that reads these columns.
  - messages_fts (FTS5 virtual table + 3 sync triggers) -> a single GIN index using pg_trgm directly on messages.text.
    Postgres's trigram index sits on the real column;
    there's no shadow table to keep in sync via triggers, so the "not itself part of the tables" caveat below shrinks to zero for search.
  - message_deletions.deleted_by_inference CHECK constraint is written directly in its final form
    ('channel_admin', 'self', 'unknown') - the intermediate ('self', 'other', 'unknown')
    and ('channel_admin', 'unknown') states from SQLite migrations 001/002 never need to exist in Postgres at all.

NOT represented in this file (deliberately - see note at bottom of module):
  - The chats denormalized-counter triggers (SQLite migration 005's five triggers).
    SQLAlchemy Core's Table object has no trigger/function abstraction - those become PL/pgSQL functions + triggers written as raw SQL directly
    in the Alembic baseline migration, not here.
"""

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    ForeignKey,
    Identity,
    Index,
    Integer,
    MetaData,
    Table,
    Text,
    TIMESTAMP,
    func,
    text,
)

# Single registry all tables attach to.
# Alembic's env.py points at this object so `alembic revision --autogenerate` can diff it against the live database.
metadata = MetaData()


# ---------------------------------------------------------------------------
# chats
# ---------------------------------------------------------------------------
# chat_type is restricted to four known values via a CHECK constraint.
# username stores the @handle for groups/channels;
# NULL for private chats and legacy groups that have no public link.
#
# message_count / deleted_count / edited_count / first_message_at / last_message_at / last_message_preview are denormalized aggregates over `messages`,
# kept in sync by triggers (see the module docstring's "NOT represented" note)
# rather than computed live on every read - see SQLite migration 005's docstring for the full "why"
# (GET /api/chats and GET /api/stats were the ones that got slow at ~460k messages).
chats = Table(
    "chats",
    metadata,
    # autoincrement=False: chat_id is Telegram's own ID,
    # supplied by the app on insert - it must NOT get a BIGSERIAL sequence (SQLAlchemy's default for any integer primary key unless told otherwise).
    Column("chat_id", BigInteger, primary_key=True, autoincrement=False),
    Column("name", Text),
    Column("username", Text),
    Column("chat_type", Text),
    Column("first_seen", TIMESTAMP(timezone=True), server_default=func.now()),
    Column("message_count", Integer, nullable=False, server_default=text("0")),
    Column("deleted_count", Integer, nullable=False, server_default=text("0")),
    Column("edited_count", Integer, nullable=False, server_default=text("0")),
    Column("first_message_at", TIMESTAMP(timezone=True)),
    Column("last_message_at", TIMESTAMP(timezone=True)),
    Column("last_message_preview", Text),
    CheckConstraint(
        "chat_type IN ('group', 'supergroup', 'channel', 'private')",
        name="ck_chats_chat_type",
    ),
    # chats is small (hundreds/thousands of rows, not hundreds of thousands) - this index is "cheap insurance" rather than load-bearing,
    # same as its SQLite counterpart in migration 005.
    Index("idx_chats_last_message_at", "last_message_at"),
)


# ---------------------------------------------------------------------------
# senders
# ---------------------------------------------------------------------------
# Stores Telegram user identity at the time first encountered.
# username may be NULL (not every user sets a @handle).
senders = Table(
    "senders",
    metadata,
    # autoincrement=False: same reasoning as chats.chat_id above.
    Column("sender_id", BigInteger, primary_key=True, autoincrement=False),
    Column("username", Text),
    Column("first_name", Text),
    Column("last_name", Text),
    Column("first_seen", TIMESTAMP(timezone=True), server_default=func.now()),
)


# ---------------------------------------------------------------------------
# messages
# ---------------------------------------------------------------------------
# Core archive table.
# tg_message_id is Telegram's ID, which is only unique within a single chat, so the uniqueness constraint is on the
# (tg_message_id, chat_id) pair - Telegram reuses message IDs across different chats.
# sender_id is NULL for channel posts (no individual author).
# archived_at records when TeleVault stored the row, distinct from date (when Telegram says the message was sent).
messages = Table(
    "messages",
    metadata,
    Column("id", BigInteger, Identity(), primary_key=True),
    Column("tg_message_id", BigInteger, nullable=False),
    Column("chat_id", BigInteger, ForeignKey("chats.chat_id"), nullable=False),
    Column("sender_id", BigInteger, ForeignKey("senders.sender_id")),
    Column("text", Text),
    Column("date", TIMESTAMP(timezone=True), nullable=False),
    Column("is_edited", Boolean, nullable=False, server_default=text("false")),
    Column("edited_at", TIMESTAMP(timezone=True)),
    Column("is_deleted", Boolean, nullable=False, server_default=text("false")),
    Column("deleted_at", TIMESTAMP(timezone=True)),
    Column("archived_at", TIMESTAMP(timezone=True), server_default=func.now()),
    # Was a UNIQUE INDEX in SQLite;
    # a unique Index does the same job here and keeps the exact original name instead of renaming it to a constraint.
    Index("idx_messages_tg_id_chat", "tg_message_id", "chat_id", unique=True),
    # Read-path indexes (SQLite migration 004's rationale, unchanged):
    # covers get_chat_messages()'s WHERE chat_id = ? ORDER BY date DESC, and get_chats()'s per-chat aggregation.
    Index("idx_messages_chat_date", "chat_id", "date"),
    # Covers get_messages()'s global feed ORDER BY date DESC with no chat_id filter.
    Index("idx_messages_date", "date"),
    # Covers the sender_id filter in get_messages()/get_chat_messages().
    Index("idx_messages_sender", "sender_id"),
    # Partial indexes: is_deleted/is_edited are each a small fraction of all rows in a real archive
    # (52 deleted / 359 edited out of 458931 total, per the original SQLite testing),
    # so these only need to cover that fraction instead of a full table scan for a handful of matches.
    Index(
        "idx_messages_is_deleted_partial",
        "chat_id",
        "date",
        postgresql_where=Column("is_deleted", Boolean).is_(True),
    ),
    Index(
        "idx_messages_is_edited_partial",
        "chat_id",
        "date",
        postgresql_where=Column("is_edited", Boolean).is_(True),
    ),
    # Replaces messages_fts (SQLite FTS5 virtual table + 3 sync triggers, migration 004) with a single GIN trigram index sitting directly on this column.
    # Same "substring anywhere, including mid-word, Cyrillic-friendly" search behaviour as before, with no shadow table to keep in sync.
    # Requires the pg_trgm extension (confirmed enabled - see docker/init/01-extensions.sql).
    Index(
        "idx_messages_text_trgm",
        "text",
        postgresql_using="gin",
        postgresql_ops={"text": "gin_trgm_ops"},
    ),
)


# ---------------------------------------------------------------------------
# message_edits
# ---------------------------------------------------------------------------
# Stores the full before/after text each time a message is edited - a complete revision history, not just "was it ever edited".
# Linked to messages.id (the app's internal ID, not Telegram's).
message_edits = Table(
    "message_edits",
    metadata,
    Column("id", BigInteger, Identity(), primary_key=True),
    Column("message_id", BigInteger, ForeignKey("messages.id"), nullable=False),
    Column("old_text", Text),
    Column("new_text", Text),
    Column("edited_at", TIMESTAMP(timezone=True), server_default=func.now()),
    Index("idx_message_edits_message_id", "message_id"),
)


# ---------------------------------------------------------------------------
# message_deletions
# ---------------------------------------------------------------------------
# Mirrors message_edits but for deletions.
# Stores a snapshot of the text at deletion time so the record is self-contained - useful even if messages.text is later modified.
#
# deleted_at is passed explicitly from Python rather than relying on a DB default - same as before,
# but now that this is TIMESTAMPTZ instead of a TEXT column, that Python value needs to be a timezone-aware datetime (e.g. datetime.now(timezone.utc)).
# A naive datetime would be silently assumed to be in the session's timezone by Postgres - worth double-checking when the handler call sites are touched.
#
# deleted_by_inference is written directly in its final, settled form here
# (SQLite migrations 001-003 arrived at this same end state incrementally; see this module's docstring for that history).
# Telegram gives no reliable way to know who deleted a message in an ordinary private/group chat,
# so 'self' is only ever inferred for Saved Messages, and 'channel_admin' only for broadcast channels
# (where deletion is structurally admin-only) - see db/queries.py's flag_deleted() for where this is computed.
message_deletions = Table(
    "message_deletions",
    metadata,
    Column("id", BigInteger, Identity(), primary_key=True),
    Column("message_id", BigInteger, ForeignKey("messages.id"), nullable=False),
    Column("text_snapshot", Text),
    Column("deleted_at", TIMESTAMP(timezone=True)),
    Column(
        "deleted_by_inference",
        Text,
        nullable=False,
        server_default="unknown",
    ),
    Column("inference_confidence", Text),
    CheckConstraint(
        "deleted_by_inference IN ('channel_admin', 'self', 'unknown')",
        name="ck_message_deletions_deleted_by_inference",
    ),
    Index("idx_message_deletions_message_id", "message_id"),
)


# ---------------------------------------------------------------------------
# chat_migrations
# ---------------------------------------------------------------------------
# Populated when a basic group upgrades to a supergroup, detected either live
# (MessageActionChatMigrateTo/MessageActionChannelMigrateFrom service messages) or during backfill (ChannelFull.migrated_from_chat_id).
# Read by queries.resolve_chat_id() so every future write is canonicalized automatically.
chat_migrations = Table(
    "chat_migrations",
    metadata,
    # autoincrement=False: same reasoning as chats.chat_id above.
    Column("old_chat_id", BigInteger, primary_key=True, autoincrement=False),
    Column("new_chat_id", BigInteger, nullable=False),
    Column("migrated_at", TIMESTAMP(timezone=True), server_default=func.now()),
)


# ---------------------------------------------------------------------------
# backfill_runs
# ---------------------------------------------------------------------------
# Records each time a backfill is run - progress, totals, and outcome.
backfill_runs = Table(
    "backfill_runs",
    metadata,
    Column("id", BigInteger, Identity(), primary_key=True),
    Column("started_at", TIMESTAMP(timezone=True), server_default=func.now()),
    Column("finished_at", TIMESTAMP(timezone=True)),
    Column("status", Text),
    Column("chat_selector", Text),
    Column("chats_total", Integer),
    Column("chats_done", Integer, server_default=text("0")),
    Column("messages_stored", Integer, server_default=text("0")),
    Column("messages_skipped", Integer, server_default=text("0")),
    Column("error_message", Text),
    CheckConstraint(
        "status IN ('running', 'completed', 'cancelled', 'error')",
        name="ck_backfill_runs_status",
    ),
)


# ---------------------------------------------------------------------------
# Deliberately NOT in this file
# ---------------------------------------------------------------------------
# 1. No `apply_schema()` entry point.
#    In the SQLite era this module was imported and called at every startup (main.py:124, backfill.py:215) to create tables and run db/migrations/*.
#    Under Alembic, schema application becomes `alembic upgrade head`, run explicitly (deploy step / CLI), not a function called from application code on every boot.
#    main.py:124 and backfill.py:215 still call db.apply_schema(conn) as of this file - those call sites will need to change.
#    Flagging now so it isn't lost;
#    not touching them yet (connection.py rework and handler call sites), not this schema translation.
# 2. No PL/pgSQL trigger functions for the chats denormalized counters (SQLite migration 005's five triggers).
#    SQLAlchemy Core's Table object has no trigger/function abstraction - these will be written as raw SQL
#    (CREATE FUNCTION + CREATE TRIGGER) directly in the Alembic baseline migration, alongside the enabling of the pg_trgm extension.