"""add revoked_reason to refresh_tokens

Revision ID: 3be4e8d18aa0
Revises: 2309be6e2eee
Create Date: 2026-09-15 10:22:13.714781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be4e8d18aa0'
down_revision: Union[str, Sequence[str], None] = '2309be6e2eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked_reason')
    # ### end Alembic commands ###